### ISSUE TITLE
Multidex enable needed 

### ISSUE THREAD

**Issue by nhoxbypass** [Pradyuman7/TrackEyes#3]
I've got this error when building the app

```
AGPBI: {"kind":"error","text":"Cannot fit requested classes in a single dex file. Try supplying a main-dex list.\n# methods: 66947 \u003e 65536","sources":[{}],"tool":"D8"}
:app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  The number of method references in a .dex file cannot exceed 64K.
  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
```

I think we need to enable **Multidex** for this app (over 64K methods).

**Comment by amy1602** [comment]
The same issue :((

**Comment by Pradyuman7** [comment]
Did you put the dependencies in the correct file, if you're confused about some part of it or are stuck at some place, do refer the post which explains how to do this step by step, 
https://medium.com/@pradyumandixit/make-an-eye-tracking-and-face-detection-app-as-a-beginner-d72e0139546b

**Comment by nhoxbypass** [comment]
I didn't edit anything, just clone this repo & run, then I got this error.

**Comment by Pradyuman7** [comment]
I think this issue might be due to google play services update, try updating it to the latest stable version. I hope it works, if it doesn't, you can add following code in your **app/build.grade**
```
android {
    defaultConfig {
       multiDexEnabled true
    }
}
```

**Comment by Pradyuman7** [comment]
The above solution seems to have solved the problems. Cheers! :) Happy Learning!
